CI: Fix Homebrew trust
These Homebrew PRs means that we have to trust the real URL, not just
`desy/crystfel`:
https://github.com/Homebrew/brew/pull/22590
https://github.com/Homebrew/brew/pull/22611

The tap has to be trusted before we run 'brew tap' (..!) otherwise Brew
will refuse to parse the formulae for the dependencies, because they are
themselves in an as-yet untrusted tap.  This produces a barrage of error
messages:

```
Error: Invalid formula (x86_64_linux): /opt/homebrew/Library/Taps/desy/homebrew-crystfel/Formula/libccp4.rb
Refusing to load formula desy/crystfel/libccp4 from untrusted tap desy/crystfel.
Run `brew trust --formula desy/crystfel/libccp4` or `brew trust desy/crystfel` to trust it.
Error: Invalid formula (x86_64_linux): /opt/homebrew/Library/Taps/desy/homebrew-crystfel/Formula/mille.rb
Refusing to load formula desy/crystfel/mille from untrusted tap desy/crystfel.
Run `brew trust --formula desy/crystfel/mille` or `brew trust desy/crystfel` to trust it.
Error: Invalid formula (x86_64_linux): /opt/homebrew/Library/Taps/desy/homebrew-crystfel/Formula/millepede2.rb
Refusing to load formula desy/crystfel/millepede2 from untrusted tap desy/crystfel.
Run `brew trust --formula desy/crystfel/millepede2` or `brew trust desy/crystfel` to trust it.
Error: Invalid formula (x86_64_linux): /opt/homebrew/Library/Taps/desy/homebrew-crystfel/Formula/pinkindexer.rb
Refusing to load formula desy/crystfel/pinkindexer from untrusted tap desy/crystfel.
Run `brew trust --formula desy/crystfel/pinkindexer` or `brew trust desy/crystfel` to trust it.
....
Error: Cannot tap desy/crystfel: invalid syntax in tap!
```

The error messages are unhelpful.  You can't run `brew trust desy/crystfel` because
Brew has refused to recognise the tap, and we are using a custom URL for
the tap (not GitHub) so it won't know what we mean.  The correct answer
is to run `brew trust https://gitlab.desy.de/thomas.white/homebrew-crystfel.git/`
*before* running `brew tap desy/crystfel https:/.....`.

Just to make sure things aren't too easy, the `brew trust` command has
to use the 'real' address after a redirection:

```
warning: redirecting to https://gitlab.desy.de/thomas.white/homebrew-crystfel.git/
==> Redirected tap desy/crystfel remote to https://gitlab.desy.de/thomas.white/homebrew-cr
```